version: '3'
services:
  webcam-app:
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTH}
    volumes:
      - ${XSOCK}:${XSOCK}
      - ${XAUTH}:${XAUTH}
    devices:
      - /dev/video0:/dev/video0
    tty: true
    stdin_open: true
